#!/usr/bin/env python3
"""
yemi-shell terminal color fan-out
Reads ~/.cache/yemi-shell/terminal.json (single source of truth)
and writes theme files for every terminal emulator.

Adding a new terminal: add one function + call it in main().
"""

import json
import os
import subprocess
import sys
from pathlib import Path

CACHE = Path.home() / ".cache" / "yemi-shell"
TERMINAL_JSON = CACHE / "terminal.json"


def load_colors() -> dict:
    if not TERMINAL_JSON.exists():
        print(f"[yemi-shell] terminal.json not found at {TERMINAL_JSON}", file=sys.stderr)
        sys.exit(1)
    with open(TERMINAL_JSON) as f:
        return json.load(f)


# ── Kitty ─────────────────────────────────────────────────────────────────────

def write_kitty(c: dict):
    """Write ~/.config/kitty/theme.conf — kitty.conf must contain: include theme.conf"""
    # term0 is matugen's tinted dark — override with pure black so the
    # background has no colour cast (opacity + blur provide the wallpaper feel)
    bg = "#000000"
    lines = [
        "# Auto-generated by apply-terminal-colors.py — do not edit",
        "# Source: ~/.cache/yemi-shell/terminal.json",
        "",
        f'foreground              {c["term15"]}',
        f'background              {bg}',
        f'selection_foreground    {bg}',
        f'selection_background    {c["term15"]}',
        f'cursor                  {c["primary"]}',
        f'cursor_text_color       {bg}',
        f'url_color               {c["primary"]}',
        f'active_border_color     {c["primary"]}',
        f'inactive_border_color   {c["term8"]}',
        "",
        f'color0  {bg}',
        f'color8  {c["term8"]}',
        f'color1  {c["term1"]}',
        f'color9  {c["term9"]}',
        f'color2  {c["term2"]}',
        f'color10 {c["term10"]}',
        f'color3  {c["term3"]}',
        f'color11 {c["term11"]}',
        f'color4  {c["term4"]}',
        f'color12 {c["term12"]}',
        f'color5  {c["term5"]}',
        f'color13 {c["term13"]}',
        f'color6  {c["term6"]}',
        f'color14 {c["term14"]}',
        f'color7  {c["term7"]}',
        f'color15 {c["term15"]}',
    ]
    out = Path.home() / ".config" / "kitty" / "theme.conf"
    out.write_text("\n".join(lines) + "\n")
    print(f"[yemi-shell] kitty → {out}")


# ── Ghostty ───────────────────────────────────────────────────────────────────

def write_ghostty(c: dict):
    """Write ~/.config/ghostty/themes/yemi-auto — ghostty config must contain: theme = yemi-auto"""
    bg = "#000000"
    lines = [
        "# Auto-generated by apply-terminal-colors.py — do not edit",
        "# Source: ~/.cache/yemi-shell/terminal.json",
        "",
        f'background = {bg}',
        f'foreground = {c["term15"]}',
        f'cursor-color = {c["primary"]}',
        f'cursor-text = {bg}',
        f'selection-background = {c["term8"]}',
        f'selection-foreground = {c["term15"]}',
        "",
        f'palette = 0={bg}',
        f'palette = 1={c["term1"]}',
        f'palette = 2={c["term2"]}',
        f'palette = 3={c["term3"]}',
        f'palette = 4={c["term4"]}',
        f'palette = 5={c["term5"]}',
        f'palette = 6={c["term6"]}',
        f'palette = 7={c["term7"]}',
        f'palette = 8={c["term8"]}',
        f'palette = 9={c["term9"]}',
        f'palette = 10={c["term10"]}',
        f'palette = 11={c["term11"]}',
        f'palette = 12={c["term12"]}',
        f'palette = 13={c["term13"]}',
        f'palette = 14={c["term14"]}',
        f'palette = 15={c["term15"]}',
    ]
    out = Path.home() / ".config" / "ghostty" / "themes" / "yemi-auto"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"[yemi-shell] ghostty → {out}")


# ── Signal terminals ──────────────────────────────────────────────────────────

def reload_kitty():
    try:
        subprocess.run(["pkill", "--signal", "SIGUSR1", "-x", "kitty"],
                       capture_output=True, timeout=2)
        print("[yemi-shell] kitty reloaded (SIGUSR1)")
    except Exception:
        pass


def reload_ghostty():
    try:
        subprocess.run(["pkill", "--signal", "SIGUSR2", "-x", "ghostty"],
                       capture_output=True, timeout=2)
        print("[yemi-shell] ghostty reloaded (SIGUSR2)")
    except Exception:
        pass


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    c = load_colors()

    write_kitty(c)
    write_ghostty(c)

    reload_kitty()
    reload_ghostty()


if __name__ == "__main__":
    main()
