foreground            #e3e2e4
background            #121415
selection_foreground  #0c344a
selection_background  #a8cbe7
url_color             #eebd8d
cursor                #a8cbe7
cursor_text_color     #0c344a

color0   #121415
color1   #ffb4ab
color2   #a8cbe7
color3   #eebd8d
color4   #a8cbe7
color5   #eebd8d
color6   #75512a
color7   #e3e2e4

color8   #8c9197
color9   #ffb4ab
color10  #a8cbe7
color11  #eebd8d
color12  #a8cbe7
color13  #eebd8d
color14  #75512a
color15  #e3e2e4

tab_bar_background              #121415
tab_bar_margin_color            #121415
active_tab_foreground           #0c344a
active_tab_background           #a8cbe7
inactive_tab_foreground         #c2c7cd
inactive_tab_background         #121415
